services:
  scraper:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/w2a-scraper/app
    ports:
      - 5000:5000
    tty: true
    depends_on:
      - db
      - chatbot-chromadb
  db:
    env_file: .env
    image: postgres:latest
    ports:
      - 5432:5432
  chatbot-chromadb:
    image: chromadb/chroma:0.5.7
    volumes:
      - chatbot-chromaDB-volume:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}
      - ALLOW_RESET=TRUE
    ports:
      - 8001:8000
    networks:
      - default
  ai-description:
    build:
      context: ./ai-description-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    tty: true

volumes:
  chatbot-chromaDB-volume:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
