services:
  web:
    env_file: .env.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/w2a-scraper/app
    ports:
      - 5000:5000
    tty: true
    depends_on:
      - db
  db:
    env_file: .env.dev
    image: postgres:latest
    ports:
      - 5432:5432
    # we can add volume if we want to preserve the data
