services:
  web:
    env_file: .env.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/w2a-scraper/app
    ports:
      - 5000:5000
    tty: true
    depends_on:
      - db
  db:
    env_file: .env.dev
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /path/to/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

volumes:
  postgres_data:
