FROM python:3.12.2

WORKDIR /w2a-scraper/app

COPY config/requirements.txt config/requirements.txt
RUN pip3 install -r config/requirements.txt

ENV FLASK_APP=app
ENV FLASK_ENV=development

WORKDIR /w2a-scraper/app/src

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--debug"]