services:
  web:
    env_file: .env.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/w2a-scraper/app
    ports:
      - 5000:5000
    tty: true
    depends_on:
      - db
  db:
    env_file: .env.dev
    image: postgres:latest
    ports:
      - 5432:5432
  chatbot-chromadb:
    image: chromadb/chroma:0.5.7
    volumes:
      - chatbot-chromaDB-volume:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}
    ports:
      - 8001:8000

volumes:
  chatbot-chromaDB-volume:
