name: Python Code Quality Checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r config/requirements.txt

      - name: Run Black
        run: black --check .

      - name: Run Mypy
        run: mypy .

      - name: Run isort
        run: isort --check-only .

      - name: Run Bandit
        run: bandit -r .
